/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'Ali' at '9/29/16 11:31 AM' with Gradle 2.14.1
 *
 * @author Ali, @date 9/29/16 11:31 AM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
