//import org.junit.Test;
//import static org.junit.Assert.*;
//
///*
// * This Java source file was auto generated by running 'gradle init --type java-library'
// * by 'Ali' at '9/29/16 11:31 AM' with Gradle 2.14.1
// *
// * @author Ali, @date 9/29/16 11:31 AM
// */
//public class LibraryTest {
//    @Test public void testSomeLibraryMethod() {
//        Library classUnderTest = new Library();
//        assertTrue("someLibraryMethod should return 'true'", classUnderTest.someLibraryMethod());
//    }
//}
